CREATE TABLE "public"."Student" (
  id SERIAL PRIMARY KEY NOT NULL,
  fullname VARCHAR(255) NOT NULL,
  csc472 INTEGER NOT NULL,
  csc431 INTEGER NOT NULL,
  csc451 INTEGER NOT NULL,
  csc333 INTEGER NOT NULL,
  csc334 INTEGER NOT NULL
);
